spring:
  elasticsearch:
    connection-timeout: 10s # 连接超时时间
    username:  # 连接用户名
    password:   # 连接密码
    socket-timeout: 30s  # 读取超时时间
    uris: ${ES_HOST:localhost}:${ES_PORT:9200} # es rest 接口地址，多个用逗号隔

