rocketmq:
  name-server: 127.0.0.1:9876 # 访问地址
  producer:
    #生产者组名字
    group: Pro_Group # 必须指定group
    # 消息最大长度 默认 1024 * 4 (4M)
    max-message-size: 4096
    send-message-timeout: 15000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2


